### np.save and np.load 

In [1]:
import numpy as np
arr = np.arange(10)
np.save('some_array', arr)

In [7]:
np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### using np.savez to save multiple arrays

In [14]:
brr = np.random.randn(10)
np.savez('array_archive.npz', a=arr, b=brr)

In [15]:
arch = np.load('array_archive.npz')

In [18]:
arch['b']

array([-0.52207647, -0.13589413,  0.27270592,  0.38519094, -0.9513904 ,
       -1.71465737,  0.57884476,  1.82348016, -0.50287037,  0.21794549])

### linear Algebra

In [2]:
x = np.array([[1.,2.,3.], [4.,5.,6.]])
y = np.array([[6.,23.], [-1, 7], [8, 9]])

In [3]:
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [4]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [7]:
%time x.dot(y)

Wall time: 0 ns


array([[ 28.,  64.],
       [ 67., 181.]])

In [9]:
%time np.dot(x, y)

Wall time: 0 ns


array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
x @ np.ones(3)

array([ 6., 15.])

In [44]:
from numpy.linalg import inv, qr, det

In [27]:
x = np.random.randn(5,5)*5
mat = x.T.dot(x)
mat = mat.astype(np.int32)
mat

array([[ 61, -19,  43, -26,  13],
       [-19,  19, -11,   2,  12],
       [ 43, -11,  71,   7,  17],
       [-26,   2,   7, 250, -79],
       [ 13,  12,  17, -79,  46]])

In [29]:
inv(mat)

array([[ 0.06888456,  0.18861824,  0.02910708, -0.0443021 , -0.15551314],
       [ 0.18861824,  1.06760878,  0.31350073, -0.30431933, -0.97030613],
       [ 0.02910708,  0.31350073,  0.13025701, -0.10230074, -0.31383757],
       [-0.0443021 , -0.30431933, -0.10230074,  0.09989271,  0.30126948],
       [-0.15551314, -0.97030613, -0.31383757,  0.30126948,  0.95219288]])

In [35]:
mat.dot(inv(mat)).astype(np.int64)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [40]:
q,r = qr(mat)
r

array([[ -82.31646251,   22.94802209,  -71.9661635 ,  107.51190868,
         -47.96124469],
       [   0.        ,  -21.54967012,   -2.89939983,  114.16349493,
         -59.79746769],
       [   0.        ,    0.        ,  -46.49155613, -168.46554231,
          37.89857108],
       [   0.        ,    0.        ,    0.        , -128.44160919,
          40.57333014],
       [   0.        ,    0.        ,    0.        ,    0.        ,
           0.69646143]])

In [42]:
x.trace()

4.657383675390842

In [45]:
det(x)

-1185.0606014571028