In [1]:
import numpy as np

In [4]:
samples = np.random.normal(size=(4,4))

In [5]:
samples

array([[ 0.57066259,  0.26030571,  0.66806705, -1.46737203],
       [-1.79258217,  0.0803154 , -1.26404541, -1.77853581],
       [-2.47693175, -1.54773145, -0.19492598, -0.69696671],
       [-0.9472199 ,  0.09021485, -0.98579766, -0.14692619]])

In [7]:
from random import normalvariate
N = 1000000

In [11]:
%timeit sample = [normalvariate(0, 1) for _ in range(N)]

707 ms ± 17.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%timeit np.random.normal(size=N)

26.2 ms ± 131 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [21]:
z = np.random.uniform(0, 12, size=19)
z.sort()

In [22]:
z

array([ 1.10484014,  1.67403549,  3.05808522,  3.09804165,  4.07533136,
        4.18720377,  4.63320333,  4.8560737 ,  6.30397275,  6.62065788,
        7.40493487,  7.93328363,  8.92790498,  9.01452431,  9.10409696,
        9.90261023, 10.56518862, 10.72444287, 11.42144503])

### random walk

In [47]:
nwalks = 5000
nsteps = 1000
ndraws = np.random.randint(0, 2, size=(nwalks, nsteps))
steps = np.where(ndraws>0, 1, -1)
walks = steps.cumsum(1)

In [48]:
walks

array([[  1,   0,   1, ...,  36,  37,  38],
       [ -1,  -2,  -3, ...,  14,  13,  14],
       [  1,   0,  -1, ..., -48, -49, -48],
       ...,
       [  1,   2,   3, ...,   0,   1,   0],
       [ -1,  -2,  -3, ...,  32,  31,  32],
       [ -1,  -2,  -3, ...,  -8,  -7,  -8]], dtype=int32)

In [49]:
walks.max()

132

In [54]:
hits30 = (np.abs(walks)>=30).any(1)

In [55]:
hits30

array([ True,  True,  True, ..., False,  True, False])

In [56]:
hits30.sum()

3429

In [60]:
crossing_times = (np.abs(walks[hits30]) >= 30).argmax(1)
crossing_times

array([827, 757, 431, ..., 353, 381, 753], dtype=int64)