In [1]:
import numpy as np

In [2]:
print(np.__file__)

C:\Users\15873\AppData\Roaming\Python\Python36\site-packages\numpy\__init__.py


In [3]:
my_arr = np.arange(1000000)

In [4]:
my_arr

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
type(my_arr)

numpy.ndarray

In [6]:
my_list = list(range(1000000))

In [8]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 28 ms


In [12]:
%time for _ in range(10):my_list2 = [x*2 for x in my_list]

Wall time: 739 ms


In [13]:
?

In [14]:
data = np.random.randn(2,3)

In [15]:
data

array([[-0.70202039, -0.3962887 , -0.60952258],
       [-0.3929906 ,  1.0788145 , -1.49345877]])

In [16]:
data * 10

array([[ -7.02020385,  -3.96288701,  -6.09522583],
       [ -3.92990601,  10.78814502, -14.93458768]])

In [17]:
data + data

array([[-1.40404077, -0.7925774 , -1.21904517],
       [-0.7859812 ,  2.157629  , -2.98691754]])

In [18]:
np.max(data)

1.0788145021907716

In [19]:
data.shape

(2, 3)

ndarray 里面的数据都必须是同一种类型数据

In [20]:
data.dtype

dtype('float64')

create ndarrays

In [21]:
data1 = [6,7.5,8,0,1]

In [22]:
arr1 = np.array(data1)

In [23]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [24]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [25]:
arr2 = np.array(data2)

In [26]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [27]:
arr2.ndim

2

In [32]:
arr2.dtype

dtype('int32')

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [37]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Data Types for ndarrays

dafdfadfsafasf

In [38]:
arr1 = np.array([1,2,3],dtype=np.float64)

In [39]:
arr1.dtype

dtype('float64')

In [40]:
type(arr1.dtype)

numpy.dtype

In [42]:
int_arr = arr1.astype(np.int64)

astype is used to convert dtypes

In [43]:
numeric_strings = np.array(['1.25','-9.6','42'],dtype=np.string_)

In [49]:
numeric_strings.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

In [50]:
numeric_strings.dtype

dtype('S4')

In [51]:
int_array = np.arange(10)

In [52]:
calibers = np.array([.22,.270,.357,.380,.44,.50], dtype=np.float64)

In [53]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
int_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Arrays are important because they enable you to express batch operations on data without writing any for loops

In [62]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])

In [63]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [64]:
1/arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [65]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [67]:
arr2 =  np.array([[1.,2.,4.],[4.,7.,3]])

In [68]:
arr2

array([[1., 2., 4.],
       [4., 7., 3.]])

In [70]:
arr > arr2

array([[False, False, False],
       [False, False,  True]])

In [71]:
arr = np.arange(10)

In [72]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
arr[5:8] = 12

In [75]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [76]:
arr_slice = arr[5:8]

In [77]:
arr_slice

array([12, 12, 12])

In [79]:
arr_slice[1] = 125

In [80]:
arr

array([  0,   1,   2,   3,   4,  12, 125,  12,   8,   9])

In [83]:
arr_slice[:] = 666

In [84]:
arr

array([  0,   1,   2,   3,   4, 666, 666, 666,   8,   9])

In [86]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [87]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [88]:
arr2d[2]

array([7, 8, 9])

In [89]:
arr2d[0][2]

3

In multidimensional arrays, if you omit later indices, the returned object will be a
lower dimensional ndarray consisting of all the data along the higher dimensions. So
in the 2 × 2 × 3 array arr3d:

In [90]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [91]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [92]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [93]:
old_values = arr3d[0].copy()

In [94]:
arr3d[0] = 42

In [95]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
arr3d[0] = old_values

In [97]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [98]:
arr3d[1][0]

array([7, 8, 9])

In [99]:
arr3d[1,0]

array([7, 8, 9])