In [1]:
import numpy as np

In [18]:
names = np.array(['Bob','Will', 'Joe', 'Joe','Will','Joe','Bob'])

In [19]:
data = np.random.randn(7,4)

In [20]:
names

array(['Bob', 'Will', 'Joe', 'Joe', 'Will', 'Joe', 'Bob'], dtype='<U4')

In [21]:
data

array([[ 0.62278291,  1.09440448,  0.98679335,  1.72446755],
       [-1.29175126,  0.04250107,  0.80877467, -0.83208111],
       [ 0.54885208,  0.94198867,  0.2827837 ,  1.00481847],
       [-1.48637613,  0.17295297,  2.9390798 ,  1.02917394],
       [-0.34363833,  0.96267993, -0.6404756 , -0.92410635],
       [-0.14607109, -0.69937644,  0.87899581, -0.08031224],
       [ 0.56529546,  0.5466195 , -0.09509897,  0.89023489]])

In [22]:
names == 'Bob'

array([ True, False, False, False, False, False,  True])

In [23]:
data[names == 'Bob']

array([[ 0.62278291,  1.09440448,  0.98679335,  1.72446755],
       [ 0.56529546,  0.5466195 , -0.09509897,  0.89023489]])

In [26]:
data[names == 'Bob', 3]

array([1.72446755, 0.89023489])

In [27]:
cond = names == 'Will'

In [28]:
cond

array([False,  True, False, False,  True, False, False])

In [29]:
data[~cond]

array([[ 0.62278291,  1.09440448,  0.98679335,  1.72446755],
       [ 0.54885208,  0.94198867,  0.2827837 ,  1.00481847],
       [-1.48637613,  0.17295297,  2.9390798 ,  1.02917394],
       [-0.14607109, -0.69937644,  0.87899581, -0.08031224],
       [ 0.56529546,  0.5466195 , -0.09509897,  0.89023489]])

In [30]:
mask = (names == 'Bob') | (names == 'Will')

In [31]:
mask

array([ True,  True, False, False,  True, False,  True])

In [33]:
data[mask]

array([[ 0.62278291,  1.09440448,  0.98679335,  1.72446755],
       [-1.29175126,  0.04250107,  0.80877467, -0.83208111],
       [-0.34363833,  0.96267993, -0.6404756 , -0.92410635],
       [ 0.56529546,  0.5466195 , -0.09509897,  0.89023489]])

In [34]:
data[names != 'Joe'] = 7

In [35]:
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.54885208,  0.94198867,  0.2827837 ,  1.00481847],
       [-1.48637613,  0.17295297,  2.9390798 ,  1.02917394],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.14607109, -0.69937644,  0.87899581, -0.08031224],
       [ 7.        ,  7.        ,  7.        ,  7.        ]])

In [36]:
data[names != 'Joe', 2:] = 45

In [37]:
data

array([[ 7.        ,  7.        , 45.        , 45.        ],
       [ 7.        ,  7.        , 45.        , 45.        ],
       [ 0.54885208,  0.94198867,  0.2827837 ,  1.00481847],
       [-1.48637613,  0.17295297,  2.9390798 ,  1.02917394],
       [ 7.        ,  7.        , 45.        , 45.        ],
       [-0.14607109, -0.69937644,  0.87899581, -0.08031224],
       [ 7.        ,  7.        , 45.        , 45.        ]])

In [49]:
data[[-1,-2,-5]]

array([[ 7.        ,  7.        , 45.        , 45.        ],
       [-0.14607109, -0.69937644,  0.87899581, -0.08031224],
       [ 0.54885208,  0.94198867,  0.2827837 ,  1.00481847]])

In [51]:
arr = np.arange(32,dtype=np.float32)

In [60]:
arr.reshape(8,4)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.]], dtype=float32)

In [63]:
arr.ndim

1

In [73]:
arr2 = np.random.randn(8,4)

In [74]:
arr2

array([[-0.92453948,  0.81427405,  0.49557703, -0.37230806],
       [-0.87697673,  0.50566417, -0.39579967, -1.1373227 ],
       [-1.42677062, -0.21568283, -0.93564433, -1.26663752],
       [-0.11551342, -0.71370906,  0.26948066,  0.58440294],
       [-0.79859627,  0.17088283, -0.85698357,  0.61327555],
       [ 1.76249194, -0.94262537, -1.51201687, -0.37728546],
       [ 0.4966676 ,  0.96480631, -0.42036645,  2.44120814],
       [-1.77575037, -0.71624911, -2.13902915, -2.01608398]])

In [76]:
arr2[[1,5,7,2]][:, [0,3,1,2]]

array([[-0.87697673, -1.1373227 ,  0.50566417, -0.39579967],
       [ 1.76249194, -0.37728546, -0.94262537, -1.51201687],
       [-1.77575037, -2.01608398, -0.71624911, -2.13902915],
       [-1.42677062, -1.26663752, -0.21568283, -0.93564433]])

In [78]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [80]:
arr.T.shape

(4, 8)

*****When doing matrix computations, you may do this very often—for example, when
computing the inner matrix product using np.dot:






In [86]:
arr3 = np.random.randn(6,3)

In [87]:
arr3

array([[-1.55992342,  0.06679077, -0.188678  ],
       [ 0.12778716, -0.40266015, -1.67641639],
       [ 0.69850151,  0.76003055, -0.27298707],
       [ 0.70773859,  0.8188327 ,  0.59713517],
       [ 1.31239784, -0.33766714,  0.40149057],
       [ 1.06929354, -1.51131978,  0.01730647]])

In [88]:
np.dot(arr3.T, arr3)

array([[ 6.30426565, -1.1044394 ,  0.85745353],
       [-1.1044394 ,  3.81283619,  0.78217364],
       [ 0.85745353,  0.78217364,  3.43855784]])

In [89]:
arr4 = np.arange(16).reshape((2,2,4))

In [90]:
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [91]:
arr4.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [93]:
arr4.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [95]:
arr4.swapaxes(2,0)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [96]:
arr4.swapaxes(0,2)

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])